const API='/v1'; const POLL=10000; let token=localStorage.getItem('otlens_management_token')||''; let network,nodesDS,edgesDS; let assets=[],tags=[],sensors=[],graph={Nodes:[],Edges:[],HoneypotThreshold:10};
function askToken(){const v=prompt('Management token:',token);if(v!==null){token=v.trim();localStorage.setItem('otlens_management_token',token);refreshAll();}}
document.getElementById('token-btn').onclick=askToken;if(!token)setTimeout(askToken,100);
async function api(path){const r=await fetch(API+path,{headers:token?{Authorization:'Bearer '+token}:{}});if(r.status===401){setConn(false,'unauthorized');throw new Error('unauthorized')}if(!r.ok)throw new Error(await r.text());return r.json()}
function setConn(ok,msg){document.getElementById('conn-dot').className='dot '+(ok?'ok':'down');document.getElementById('conn-text').textContent=msg||(ok?'live':'backend unreachable')}
function esc(v){return String(v??'—').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]))}function time(v){if(!v)return'—';const d=new Date(v);return isNaN(d)?'—':d.toLocaleString(undefined,{hour12:false})}function val(v){return v==null?'—':Array.isArray(v)?v.join(', '):typeof v==='object'?JSON.stringify(v):String(v)}
document.getElementById('tabs').onclick=e=>{const b=e.target.closest('.tab');if(!b)return;document.querySelectorAll('.tab').forEach(x=>x.classList.remove('active'));b.classList.add('active');document.querySelectorAll('.view').forEach(x=>x.classList.remove('active'));document.getElementById('view-'+b.dataset.tab).classList.add('active');if(b.dataset.tab==='topology'&&network)setTimeout(()=>network.redraw(),50)};
function renderAssets(){const q=document.getElementById('assets-filter').value.toLowerCase();const data=assets.filter(a=>JSON.stringify(a).toLowerCase().includes(q));document.getElementById('assets-count').textContent=data.length+' assets';const tb=document.querySelector('#table-assets tbody');tb.innerHTML=data.map(a=>`<tr><td>${esc(a.SensorID)}</td><td>${esc(a.IP)}</td><td>${esc(a.MAC)}</td><td>${esc(a.Vendor)}</td><td>${esc(a.Hostname)}</td><td><span class="severity ${a.IsOT?'medium':'low'}">${a.IsOT?'OT':'IT'}</span></td><td>${esc((a.Protocols||[]).join(', '))}</td><td>${esc(a.VLANID||'untagged')}</td><td>${esc(a.PacketCount)}</td><td>${time(a.LastSeen)}</td></tr>`).join('');document.querySelector('#view-assets .empty-state').hidden=data.length>0}
function renderTags(){const q=document.getElementById('tags-filter').value.toLowerCase();const data=tags.filter(t=>JSON.stringify(t).toLowerCase().includes(q));document.getElementById('tags-count').textContent=data.length+' tags';const tb=document.querySelector('#table-tags tbody');tb.innerHTML=data.map(t=>`<tr><td>${esc(t.SensorID)}</td><td>${esc(t.DeviceIP)}:${esc(t.DevicePort)}</td><td>${esc(t.Protocol)}</td><td>${esc(t.AddressSpace)} ${esc(t.Address)}</td><td>${esc(t.Operation)}</td><td>${esc(val(t.LastValue))}</td><td>${esc(val(t.PreviousValue))}</td><td>${time(t.LastChangeAt)}</td><td>${esc(t.PollCount)}</td><td>${esc(t.ChangeCount)}</td></tr>`).join('');document.querySelector('#view-tags .empty-state').hidden=data.length>0}
function renderSensors(){const tb=document.querySelector('#table-sensors tbody');tb.innerHTML=sensors.map(s=>`<tr><td>${esc(s.id)}</td><td>${esc(s.name)}</td><td>${esc(s.site_id)}</td><td class="status-${esc(s.status)}">${esc(s.status)}</td><td>${esc(s.hostname)}</td><td>${esc(s.version)}</td><td>${time(s.last_seen)}</td></tr>`).join('');document.querySelector('#view-sensors .empty-state').hidden=sensors.length>0}
function node(n){const honey=(n.Score||1)>=(graph.HoneypotThreshold||10);const bg=honey?'#a855f7':n.Confirmed===false?'#e85d4c':n.IsOT?'#3fbfb0':'#64748b';return{id:n.ID,label:n.Hostname||n.IP||n.MAC,title:`Sensor: ${n.SensorID}\nIP: ${n.IP}\nMAC: ${n.MAC}\nVendor: ${n.Vendor||'—'}\nProtocols: ${(n.Protocols||[]).join(', ')||'—'}`,color:{background:bg,border:honey?'#7c3aed':n.IsOT?'#2a7d74':'#334155'},size:n.IsOT?22:16,_search:`${n.IP} ${n.MAC} ${n.Hostname} ${n.SensorID}`.toLowerCase()}}
function renderTopology(){const ns=(graph.Nodes||[]).map(node);const ipMap=new Map((graph.Nodes||[]).map(n=>[n.SensorID+'::'+n.IP,n.ID]));const es=(graph.Edges||[]).map(e=>({id:e.ID,from:ipMap.get(e.SensorID+'::'+e.SrcIP),to:ipMap.get(e.SensorID+'::'+e.DstIP),label:e.IsOT?e.Protocol:'',color:{color:e.FromHoneypot?'#e85d4c':e.IsOT?'#3fbfb0':'#64748b'},width:e.FromHoneypot?4:e.IsOT?2:1})).filter(e=>e.from&&e.to);if(!network){nodesDS=new vis.DataSet(ns);edgesDS=new vis.DataSet(es);network=new vis.Network(document.getElementById('graph'),{nodes:nodesDS,edges:edgesDS},{nodes:{shape:'dot',borderWidth:2},edges:{smooth:false},physics:{solver:'forceAtlas2Based',forceAtlas2Based:{gravitationalConstant:-120,springLength:160,avoidOverlap:1},stabilization:{iterations:250}},interaction:{hover:true,tooltipDelay:100}})}else{nodesDS.clear();edgesDS.clear();nodesDS.add(ns);edgesDS.add(es)}applySearch()}
function applySearch(){if(!network)return;const q=document.getElementById('topology-search-input').value.trim().toLowerCase();document.getElementById('topology-search-clear').hidden=!q;if(!q){network.unselectAll();document.getElementById('topology-search-status').textContent='';return}const ids=nodesDS.get().filter(n=>n._search.includes(q)).map(n=>n.id);network.selectNodes(ids);document.getElementById('topology-search-status').textContent=ids.length+' match(es)';if(ids.length===1)network.focus(ids[0],{scale:1.2,animation:true})}
document.getElementById('assets-filter').oninput=renderAssets;document.getElementById('tags-filter').oninput=renderTags;document.getElementById('topology-search-input').oninput=applySearch;document.getElementById('topology-search-clear').onclick=()=>{document.getElementById('topology-search-input').value='';applySearch()};
async function refreshAll(){try{[graph,assets,tags,sensors]=await Promise.all([api('/topology'),api('/assets'),api('/tags'),api('/sensors')]);renderTopology();renderAssets();renderTags();renderSensors();setConn(true)}catch(e){console.error(e)}}refreshAll();setInterval(refreshAll,POLL);
