package central

import (
	"archive/zip"
	"bytes"
	"encoding/json"
	"fmt"
	"net/http"
	"strconv"
	"strings"
	"time"

	"github.com/gin-gonic/gin"
)

// EndpointControl documents the server-side authorization applied to a
// sensitive management endpoint. It is intentionally generated by Central,
// so operators can audit the deployed binary instead of relying on UI hiding.
type EndpointControl struct {
	Method     string `json:"method"`
	Path       string `json:"path"`
	Permission string `json:"permission"`
	Kind       string `json:"kind"`
	Audited    bool   `json:"audited"`
}

func endpointControls() []EndpointControl {
	return []EndpointControl{
		{"POST", "/v1/sensors/actions", ActionSensorStartStop, "action", true},
		{"DELETE", "/v1/sensors/:id", ActionSensorStartStop, "action", true},
		{"POST", "/v1/reconnaissance/jobs", ActionAssetConfirmDelete, "action", true},
		{"POST", "/v1/reconnaissance/campaigns", ActionAssetConfirmDelete, "action", true},
		{"POST", "/v1/reconnaissance/campaigns/:id/run", ActionAssetConfirmDelete, "action", true},
		{"POST", "/v1/vulnerabilities/import", ActionDataManagement, "action", true},
		{"POST", "/v1/vulnerabilities/feed", ActionDataManagement, "action", true},
		{"PUT", "/v1/vulnerabilities/findings", ActionDataManagement, "action", true},
		{"PATCH", "/v1/incidents/:id", ActionAlertConfirmApprove, "action", true},
		{"POST", "/v1/incidents/:id/comments", ActionAlertConfirmApprove, "action", true},
		{"POST", "/v1/threat-intel/sources", ActionDataManagement, "action", true},
		{"POST", "/v1/threat-intel/import", ActionDataManagement, "action", true},
		{"POST", "/v1/reports/generate", ActionDataManagement, "action", true},
		{"POST", "/v1/rules/import", ActionRuleManage, "action", true},
		{"POST", "/v1/analysis/jobs", ActionAnalysisManage, "action", true},
		{"POST", "/v1/data/backups", ActionDataManagement, "action", true},
		{"POST", "/v1/data/reset", ActionDataManagement, "action", true},
		{"POST", "/v1/users", ActionUsersRolesManage, "action", true},
		{"PATCH", "/v1/users/:id", ActionUsersRolesManage, "action", true},
		{"POST", "/v1/users/:id/reset-password", ActionUsersRolesManage, "action", true},
		{"PUT", "/v1/roles", ActionUsersRolesManage, "action", true},
		{"GET", "/v1/data/diagnostics", ActionDataManagement, "action", true},
	}
}

func (s *Server) permissionAudit(c *gin.Context) {
	controls := endpointControls()
	covered := 0
	for _, item := range controls {
		if item.Permission != "" {
			covered++
		}
	}
	c.JSON(http.StatusOK, gin.H{
		"generated_at": time.Now().UTC(),
		"endpoints":    controls,
		"summary":      gin.H{"sensitive_endpoints": len(controls), "server_side_protected": covered, "unprotected": len(controls) - covered},
	})
}

func zipJSON(w *zip.Writer, name string, value interface{}) error {
	b, err := json.MarshalIndent(value, "", "  ")
	if err != nil {
		return err
	}
	f, err := w.Create(name)
	if err != nil {
		return err
	}
	_, err = f.Write(b)
	return err
}

// diagnosticsBundle exports operational state only. Password hashes, session
// tokens, management tokens, credentials and raw packet payloads are excluded.
func (s *Server) diagnosticsBundle(c *gin.Context) {
	var buf bytes.Buffer
	zw := zip.NewWriter(&buf)

	sensors, sensorErr := s.Repo.ListSensors(c)
	audit, auditErr := s.Repo.ListAuditLogFiltered(c, AuditFilter{Limit: 250})
	schemaVersion := s.Repo.SchemaVersion(c)

	manifest := gin.H{
		"generated_at":       time.Now().UTC(),
		"central_started_at": s.StartedAt,
		"schema_version":     schemaVersion,
		"runtime":            gin.H{"go": "runtime-managed", "analysis_enabled": s.AnalysisEnabled, "siem_enabled": s.SIEMEnabled},
		"errors":             []string{},
	}
	errs := []string{}
	if sensorErr != nil {
		errs = append(errs, "sensors: "+sensorErr.Error())
	}
	if auditErr != nil {
		errs = append(errs, "audit: "+auditErr.Error())
	}
	manifest["errors"] = errs

	_ = zipJSON(zw, "manifest.json", manifest)
	if sensorErr == nil {
		_ = zipJSON(zw, "sensors.json", sensors)
	}
	if auditErr == nil {
		_ = zipJSON(zw, "recent-audit.json", audit)
	}
	_ = zipJSON(zw, "permission-audit.json", gin.H{"endpoints": endpointControls()})
	_ = zipJSON(zw, "runtime-config-redacted.json", s.RuntimeConfig)
	if err := zw.Close(); err != nil {
		respondInternalError(c, err)
		return
	}

	s.logAudit(c, identityFromContext(c).Username, "diagnostics bundle exported", "")

	filename := "otlens-diagnostics-" + time.Now().UTC().Format("20060102T150405Z") + ".zip"
	c.Header("Content-Type", "application/zip")
	c.Header("Content-Disposition", fmt.Sprintf("attachment; filename=%q", filename))
	c.Header("Cache-Control", "no-store")
	c.Data(http.StatusOK, "application/zip", buf.Bytes())
}

func auditFilterFromRequest(c *gin.Context) AuditFilter {
	limit, _ := strconv.Atoi(c.DefaultQuery("limit", "250"))
	offset, _ := strconv.Atoi(c.DefaultQuery("offset", "0"))
	success := strings.TrimSpace(c.Query("success"))
	var successPtr *bool
	if success == "true" || success == "false" {
		v := success == "true"
		successPtr = &v
	}
	return AuditFilter{Limit: limit, Offset: offset, Actor: c.Query("actor"), Action: c.Query("action"), SensorID: c.Query("sensor_id"), Success: successPtr}
}
